print 'Hi this is first program to commit with repository'
print 'This is the secound line for secound commit'
print 'This is third line, and now i am pushing from pycharm'
print 'This is waste line and commited line.'
print 'This is the line added in master branch'